language: python
python:
  - 2.7
  - 3.6

sudo: false

env:
  global:
    - PYPI_PY=3.6  # deploy to pypi from python 3.6

env:
    - TEST_DIR="tests"

# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - pip install --upgrade pip

install:
  - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib ipywidgets
  # - git clone https://github.com/simpeg/simpeg.git
  # - cd simpeg; git checkout dev; git pull; python setup.py build_ext --inplace; cd ..
  # - export PATH=$PWD:$PATH
  # - export PYTHONPATH=$PWD:$PYTHONPATH

  - pip install -r requirements.txt
  - echo $PWD
  - cd ../
  - git clone https://github.com/geoscixyz/em_apps.git
  - cd em_examples
  - echo $PWD

# Run test
script:
  - nosetests $TEST_DIR

after_success:
  #deploy to pypi
  - if [ $TRAVIS_PYTHON_VERSION == $PYPI_PY -n "$TRAVIS_TAG" ]; then
      openssl aes-256-cbc -K $encrypted_99d6f572e516_key -iv $encrypted_99d6f572e516_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d;
      tar -xvzf credentials.tar.gz;
      mv credentials/.pypirc ~/.pypirc ;
      python setup.py bdist_wheel --universal ;
      travis_wait 20 twine upload -r pypi --skip-existing dist/* ;
    fi

notifications:
  slack: ubcgif:1Z2lR3XYRSM3GHflG71ZHEN6
