language: python
python:
  - 3.6

sudo: false

env:
  global:
    - PYPI_PY=3.6  # deploy to pypi from python 3.6
    - TWINE_USERNAME=lheagy

env:
  - TEST=test_dcip.py
  - TEST=test_em.py
  - TEST=test_gpr.py
  - TEST=test_inversion.py
  - TEST=test_mag.py
  - TEST=test_seismic.py
  - TEST=test_gravity.py
  - TEST=style

# Setup anaconda
before_install:
# Install packages
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda env create -f environment-dev.yml
  - source activate geosci-labs-dev
  - pip install -e .


# Run test
script:
  - if [ $TEST == "style" ]; then
      make check ;
    else
      pytest tests/$TEST -v -s ;
    fi

# upload to pypi on success and new tag
deploy:
  - provider: script
    script: ci/deploy-pypi.sh
    on:
        tags: true
        branch: master

# notify slack
notifications:
  email: false
  slack: ubcgif:1Z2lR3XYRSM3GHflG71ZHEN6
