language: python
python:
  - 3.6

sudo: false

env:
  global:
    - PYPI_PY=3.6  # deploy to pypi from python 3.6

env:
  - TEST=test_dcip.py
  - TEST=test_em.py
  - TEST=test_gpr.py
  - TEST=test_inversion.py
  - TEST=test_mag.py
  - TEST=test_seismic.py
  - TEST=style

install:
  - pip install -e .
  - pip install -r requirements-dev.txt


# Run test
script:
  - if [ $TEST = "style" ]; then
      make check ;
    else
      pytest tests/$TEST -v -s ;
    fi

# upload to pypi on success
# after_success:
#   # deploy to pypi
#   - if [ $TRAVIS_PYTHON_VERSION == $PYPI_PY ]; then
#       if [ "$TRAVIS_TAG" = "true" ]; then
#         openssl aes-256-cbc -K $encrypted_bc303f70394a_key -iv $encrypted_bc303f70394a_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d;
#         tar -xzf credentials.tar.gz;
#         mv credentials/.pypirc ~/.pypirc ;
#         python setup.py sdist bdist_wheel ;
#         travis_wait 20 twine upload -r pypi --skip-existing dist/* ;
#       fi
#     fi


# notify slack
notifications:
  slack: ubcgif:1Z2lR3XYRSM3GHflG71ZHEN6
