channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - Pillow
  - ipywidgets>=0.6.0
  - requests
  - pip:
    - pymatsolver
    - discretize
    - SimPEG
    - git+https://github.com/geoscixyz/em_examples.git@master
    - empymod
